---
- name: copy nginx config
  template:
    src: templates/joomla.j2
    dest: /etc/nginx/sites-enabled/default
  vars:
    template_nginx_app_path: "{{ nginx_app_path }}"
    # template_nginx_app_port: "{{ nginx_app_port }}"
  notify: restart nginx
...