---
- name: copy nginx config
  template:
    src: templates/joomla.j2
    dest: /etc/nginx/sites-enabled/default
  vars:
    template_nginx_app_path: "{{ nginx_app_path }}"
    template_local_php_version: "{{ local_php_version }}"
  notify: restart nginx
...