---
- name: install prequisites
  apt:
    name: 
      - php7.1-cli 
      - php7.1-gd 
      - php7.1-opcache 
      - php7.1-mysql 
      - php7.1-json 
      - php7.1-mcrypt 
      - php7.1-xml 
      - php7.1-curl
    update_cache: yes
...