---

- name: Add repository from PPA 
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: install php
  apt:
    name: 
      - "php{{ local_php_version }}" 
      - php-curl 
      - php-gd 
      - php-mbstring 
      - php-xml 
      - php-xmlrpc 
      - php-soap 
      - php-intl 
      - php-zip 
      - php-cli 
      - php-mysql 
      - php8.0-common 
      - php8.0-opcache 
      - php-gmp 
      - php-imagick 
      - openssl 
      - php-pgsql 
      - php-smbclient 
      - php-ssh2 
      - php-sqlite3
    update_cache: yes

- name: copy php config
  template:
    src: templates/php.ini.j2
    dest: "/etc/php/{{ local_php_version }}/cli/php.ini"
   
...