---

- name: Add repository from PPA 
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: install php
  apt:
    name: 
      - "php{{ local_php_version }}" 
      - "php{{ local_php_version }}-curl" 
      - "php{{ local_php_version }}-gd" 
      - "php{{ local_php_version }}-mbstring" 
      - "php{{ local_php_version }}-xml" 
      - "php{{ local_php_version }}-xmlrpc" 
      - "php{{ local_php_version }}-soap" 
      - "php{{ local_php_version }}-intl" 
      - "php{{ local_php_version }}-zip" 
      - "php{{ local_php_version }}-cli" 
#      - "php{{ local_php_version }}-mysql" 
      - "php{{ local_php_version }}-common" 
      - "php{{ local_php_version }}-opcache" 
      - "php{{ local_php_version }}-gmp" 
      - "php{{ local_php_version }}-imagick" 
      - openssl 
      - "php{{ local_php_version }}-pgsql" 
      - "php{{ local_php_version }}-smbclient" 
      - "php{{ local_php_version }}-ssh2" 
      - "php{{ local_php_version }}-sqlite3"
      - "php{{ local_php_version }}-fpm"
    update_cache: yes
#  ignore_errors: yes

- name: copy php config
  template:
    src: templates/php.ini.j2
    dest: "/etc/php/{{ local_php_version }}/cli/php.ini"
   
...