---
- name: Create home dir for joomla
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  with_items:
    - "{{ joomla_app_directory }}"

- name: Unarchive a joomla
  ansible.builtin.unarchive:
    src: https://downloads.joomla.org/cms/joomla3/3-9-18/joomla_3-9-18-stable-full_package-zip
    dest: "{{ joomla_app_directory }}"
    mode: '0755'
    owner: www-data
    group: www-data
    remote_src: yes
...