---
- name: Create home dir for joomla
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  with_items:
    - "{{ joomla_app_directory }}"

- name: Unarchive a joomla
  ansible.builtin.unarchive:
    src: https://github.com/joomla/joomla-cms/releases/download/4.2.6/Joomla_4.2.6-Stable-Full_Package.tar.gz
    dest: "{{ joomla_app_directory }}"
    mode: '0755'
    owner: www-data
    group: www-data
    remote_src: yes
