---
  - name: Add an Apt signing key
    ansible.builtin.apt_key:
      url: "{{ item }}" 
      state: present
    loop:
      - https://packagecloud.io/timescale/timescaledb/gpgkey
      - https://www.postgresql.org/media/keys/ACCC4CF8.asc

  - name: add repository
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
      - deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release|lower }}-pgdg main
        #- deb https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release|lower }}  main

  - name: Installing packages 
    ansible.builtin.package:
      name:
        - "postgresql-{{ pg_version }}"
        - "postgresql-client-{{ pg_version }}"
        - python3-venv 
        - python3-pip  
        - acl
      state: latest
      update_cache: yes
 
  - name: Install bottle python package
    ansible.builtin.pip:
      name: psycopg2-binary

  - name: Change postgres config files
    template:
      src: "{{ item }}"
      dest: "{{ pg_config_path }}"
      mode: '0644'
      owner: "{{ pg_user }}"
      group: "{{ pg_user }}"
    with_items:
      - templates/pg_hba.conf      
      - templates/postgresql.conf

  - name: Start and enable services
    service: 
      name: postgresql
      state: restarted 
      enabled: yes

...

