---
- name: app
  hosts: app
  gather_facts: no
  become: yes

  tasks:
    - name: include joomla role
      include_role:
        name: joomla
            
    # - name: include uwsgi role (pytime)
    #   include_role:
    #     name: uwsgi
    #     tasks_from: pytime.yml
    #   vars:
    #     uwsgi_app_directory:  "{{ local_pytime_directory }}"
    #     uwsgi_app_socket:     "{{ local_pytime_socket }}"

    # - name: include pytime role
    #   include_role:
    #     name: pytime
    #   vars:
    #     pytime_app_directory:   "{{ local_pytime_directory }}"
    #     pytime_app_redis_bind:  "{{ local_pytime_redis_bind }}"
...