---
- name: app
  hosts: app
  gather_facts: no
  become: yes

  tasks:
    - name: include joomla role
      include_role:
        name: joomla
        tasks_from: php.yml
      vars:
        local_php_version: "{{ php_version }}"
        
    
    - name: include joomla role
      include_role:
        name: joomla
        tasks_from: unpack_joomla.yml
      vars:
        joomla_app_directory: "{{ local_joomla_directory }}"
    
...