---
- name: database
  hosts: db
  gather_facts: no
  become: yes

  tasks:
    - name: include pg role
      include_role:
        name: pg

    - name: include pg role (user)
      include_role:
        name: pg
        tasks_from: user.yml
...
