---
- name: front
  hosts: front
  gather_facts: no
  become: yes

  tasks:
    - name: include nginx role
      include_role:
        name: nginx

    - name: include nginx role (joomla)
      include_role:
        name: nginx
        tasks_from: joomla.yml
      vars:
        nginx_app_path: "{{ local_joomla_directory }}"
        local_php_version: "{{ php_version }}"
...
