---
- name: front
  hosts: front
  gather_facts: no
  become: yes

  tasks:
    - name: include nginx role
      include_role:
        name: nginx

    - name: include nginx role (joomla)
      include_role:
        name: nginx
        tasks_from: joomla.yml
      vars:
        nginx_app_socket: "{{ local_joomla_socket }}"
...
