---
# vars file for postgres-install

db_user: forsite
db_password: forsite
db_name: forsite
pg_user: postgres
pg_password: $6$wLBqdYLR8F..sbhZ$OLAy85eJhjymOoME59Rr84po/a/BocHQ4hyHgg/UT/ReFYxR5V68ktwPR0A.1qEliZ8Tktj5yPB06ypGrXr6v.
pg_config_path: /etc/postgresql/14/main
pg_version: 14
